export const INDUSTRIES = [
  "Automotive",
  "Beverage",
  "Cosmetics",
  "Education",
  "Electronics",
  "Entertainment",
  "Fashion",
  "Finance",
  "Food",
  "Healthcare",
  "Hospitality",
  "Insurance",
  "Logistics",
  "Pharmaceutical",
  "Retail",
  "Sports",
  "Technology",
  "Telecom",
  "Travel",
  "Other",
];

export const COUNTRY_CODES = [
  { code: "US", dial: "+1" },
  { code: "CA", dial: "+1" },
  { code: "MX", dial: "+52" },
  { code: "FR", dial: "+33" },
  { code: "DE", dial: "+49" },
  { code: "ES", dial: "+34" },
  { code: "IT", dial: "+39" },
  { code: "GB", dial: "+44" },
  { code: "IE", dial: "+353" },
  { code: "MA", dial: "+212" },
  { code: "DZ", dial: "+213" },
  { code: "TN", dial: "+216" },
  { code: "EG", dial: "+20" },
  { code: "SA", dial: "+966" },
  { code: "AE", dial: "+971" },
  { code: "QA", dial: "+974" },
  { code: "KW", dial: "+965" },
  { code: "BH", dial: "+973" },
  { code: "OM", dial: "+968" },
  { code: "TR", dial: "+90" },
  { code: "IN", dial: "+91" },
  { code: "CN", dial: "+86" },
  { code: "JP", dial: "+81" },
  { code: "KR", dial: "+82" },
  { code: "AU", dial: "+61" },
  { code: "NZ", dial: "+64" },
  { code: "BR", dial: "+55" },
  { code: "AR", dial: "+54" },
  { code: "CL", dial: "+56" },
  { code: "CO", dial: "+57" },
  { code: "ZA", dial: "+27" },
  { code: "NG", dial: "+234" },
  { code: "KE", dial: "+254" },
];
